# Generated by Django 4.0.6 on 2022-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('arabic', models.CharField(max_length=100)),
            ],
        ),
    ]
