# Generated by Django 4.0.6 on 2022-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('arabic', models.CharField(max_length=100)),
                ('field', models.CharField(blank=True, choices=[('geometry', 'geometry'), ('algebra', 'algebra')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PCWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('arabic', models.CharField(max_length=100)),
                ('field', models.CharField(blank=True, choices=[('electricity', 'electricity'), ('mechanics', 'mechanics')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SVTWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('french', models.CharField(max_length=100)),
                ('arabic', models.CharField(max_length=100)),
                ('field', models.CharField(blank=True, choices=[('biology', 'biology'), ('geology', 'geology')], max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
