# Generated by Django 4.0.4 on 2022-08-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pcword_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcword',
            name='field',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Electricity', 'Electricity'), ('Optics', 'Optics'), ('Waves', 'Waves'), ('Nuclear transformation', 'Nuclear transformation'), ('Matter', 'Matter'), ('Measurements in chemistry', 'Measurements in chemistry'), ('Mechanics', 'Mechanics'), ('Chemical reactions', 'Chemical reactions'), ('Organic chemistry', 'Organic chemistry')], max_length=100, null=True),
        ),
    ]
